"""rename subscription payment fields to provider agnostic

Revision ID: 724a4b641e0c
Revises: 8c5309f253d8
Create Date: 2026-07-20 14:42:20.133591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '724a4b641e0c'
down_revision: Union[str, None] = '8c5309f253d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('payment_provider', sa.String(), nullable=True))
    op.add_column('subscriptions', sa.Column('external_customer_id', sa.String(), nullable=True))
    op.add_column('subscriptions', sa.Column('external_subscription_id', sa.String(), nullable=True))
    op.drop_column('subscriptions', 'stripe_subscription_id')
    op.drop_column('subscriptions', 'stripe_customer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('stripe_customer_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('stripe_subscription_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('subscriptions', 'external_subscription_id')
    op.drop_column('subscriptions', 'external_customer_id')
    op.drop_column('subscriptions', 'payment_provider')
    # ### end Alembic commands ###
